#This is your vagrant file
Vagrant.configure("2") do | config |
    config.vm.box = "ubuntu/bionic64"
    config.vm.network :forwarded_port, guest:80, host:8080
    config.vm.network :forwarded_port, guest:8000, host:8000

    #1. this is set to rsync cause some reason it's set to two-way sync(by default)
    #2. *meaning if you change something in /vagrant it will appear in the host machine
    #3. **COMMENT THIS OUT** if you want an easy way to save your changes.
    config.vm.synced_folder '.', '/vagrant', type: "rsync"

    config.vm.provision "shell", path: "isekai_start.sh"
end
